### PR TITLE
Fix marlin macro interpretation

### LINKED ISSUE #160: Remove or reimplement `DiffLineFormulaExtractor`
During #155, I noticed that `DiffLineFormulaExtractor.resolveFeatureMacroFunctions` is currently never called (the last call was removed in 5056de8f8f04f74666ff86eb0bae8a83b7572be2) although there is still one user: `MarlinCPPDiffLineFormulaExtractor`. Should we remove the `DiffLineFormulaExtractor` interface or reimplement this feature?

### PR DESCRIPTION
**Pull request by ibbem**
From reading the code, it seems like the Marlin macro interpretation code is still injected. However, it doesn't currently have any effect as it is never called.
This PR fixes #160 and cleans up the interfaces surrounding the annotation parser. It also adds support for C23/C++23 style `#elifdef` and `#elifndef` because I noticed those are missing.

### CODE REVIEW

File: src/main/java/org/variantsync/diffdetective/datasets/predefined/Marlin.java [hunk 1]
```diff
@@ -12,10 +13,8 @@
  * @author Kevin Jedelhauser, Paul Maximilian Bittner
```
Comment (pmbittner) [inline src/main/java/org/variantsync/diffdetective/datasets/predefined/Marlin.java]: add your name please :)

File: src/test/java/CPPParserTest.java [hunk 2]
```diff
@@ -120,15 +141,30 @@ private static List<TestCase> testCases() {
...
-                new ThrowingTestCase("#error A"),
-                new ThrowingTestCase("#iferror A"),
+                new TestCase("#if ENABLED(A)", var("A")),
+                new TestCase("#if DISABLED(A)", negate(var("A"))),
+                new TestCase("#if ENABLED(FEATURE_A) && DISABLED(FEATURE_B)", and(var("FEATURE_A"), negate(var("FEATURE_B")))),
+                new TestCase("#if ENABLED(A, B)", var("ENABLED(A,B)")),
+                new TestCase("#if OTHER(A, B)", var("OTHER(A,B)")),
+                new TestCase("#if A", var("A"))
+        );
+    }
```
Comment (pmbittner) [inline src/test/java/CPPParserTest.java:164]: nice!

**Review by pmbittner — APPROVED** [review]
perfect!

**Comment by pmbittner** [comment]
So I guess integrating the Marlin-Parser is still missing right? We should add it to the default dataset loading I guess.
